-- CLASE LOCAL (SOLO PRUEBA) -------------------------------------------
-- Aislada del horario y del cierre automatico: solo guarda lo que se marca,
-- nunca genera Falta/Tardanza ni multas para nadie.

create table public.clases_locales (
  id integer primary key,
  nombre text not null,
  alumno_marca text not null,          -- quien marca (ej: AL009 Daniela)
  visible_para text[] not null default '{}',  -- quienes la ven (ej: {AL009,AL010})
  activa boolean not null default true,
  creado_en timestamptz not null default now()
);

create table public.clase_local_registros (
  id bigint generated by default as identity primary key,
  clase_local_id integer not null references public.clases_locales(id) on delete cascade,
  alumno text not null,
  fecha date not null,
  hora time not null,
  estado text not null default 'Presente' check (estado in ('Presente')),
  creado_en timestamptz not null default now(),
  unique (clase_local_id, alumno, fecha)
);

grant usage on schema public to anon, authenticated;
grant select on public.clases_locales        to anon, authenticated;
grant select on public.clase_local_registros to anon, authenticated;
grant all on public.clases_locales        to service_role;
grant all on public.clase_local_registros to service_role;

drop policy if exists "lectura_clases_locales"        on public.clases_locales;
drop policy if exists "lectura_clase_local_registros" on public.clase_local_registros;
create policy "lectura_clases_locales"        on public.clases_locales        for select using (true);
create policy "lectura_clase_local_registros" on public.clase_local_registros for select using (true);

-- Daniela HUANCA MIRANDA (AL009) marca; Jose Adolfo IBERICO SUNA (AL010) la ve.
insert into public.clases_locales (id, nombre, alumno_marca, visible_para, activa)
values (1, 'Clase local (prueba)', 'AL009', array['AL009','AL010'], true);